# vs_l515_params.yaml

# =========================================
# 相机流配置
# =========================================

# 图像宽度 (默认 640)
# 注意：必须是 L515 支持的分辨率
width: 640

# 图像高度 (默认 480)
height: 480

# 帧率 (默认 30)
# 注意：较高的帧率或分辨率可能需要 USB 3.0 接口
fps: 30

camera_frame: "camera_color_optical_frame"